
server:
  port: 8080   # porta onde acessar o servidor

swagger:
  enabled: true

aws:
  region: ${aws.region}  # região do AWS
  key: ${aws.key}        # id da credencial  AWS
  secret: ${aws.secret}  # senha da credencial AWS
